info:
  app:
    description: The CSCI 602 project from team MutInk
    name: MutInc
    version: 1.0.0
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: openapi, swagger-ui
server:
  port: 5001
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH_GITHUB_CLIENT_ID_LOCAL}
            client-secret: ${OAUTH_GITHUB_SECRET_LOCAL}
        #     authorization-grant-type: authorization_code
        #     redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        #     scope: 
        #       - read:user 
        #       - user:email
        # provider:
        #   github:
        #     authorization-uri: https://github.com/login/oauth/authorize
        #     token-uri: https://github.com/login/oauth/access_token
        #     user-info-uri: https://api.github.com/user
        #     user-name-attribute: id
  ## Allows you to go to ${BASE_URL}/h2-console to inspect db
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: mut-inc
  datasource:
    url: jdbc:h2:mem:mut-inc-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration/h2
    baseline-on-migrate: true
  mvc:
    servlet:
      load-on-startup: 1
  profiles:
    active: '@spring.profiles.active@'
springdoc:
  packagesToScan: edu.citadel.api
  pathsToMatch: /v1, /**
  show-actuator: true
