name: Java CI

on: [push]

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
      - name: Build with Maven
        run: ./mvnw -B compile --file pom.xml
      - name: Test with Maven
        run: ./mvnw -B test --file pom.xml
      - name: Test with Maven using Postgres (Persistence Profile)
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./mvnw -B test -Dspring.profiles.active=persistence --file pom.xml
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push image to ghcr.io
        run: mvn -B package -Dmaven.test.skip=true -Pghcr-push
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
